#!/usr/bin/env python3
"""Emit the public-repo (sanitized) fact-recall summary from a private report.

The full fact-recall report lives in the private corpus repo with real cluster
ids and per-fact audit data. This script renders the public-facing markdown
summary with ANONYMIZED cluster ids (cluster-1..N in golden-file order), numbers
only -- no private codenames, fact texts, or infrastructure references can leak
into the public repo (the leak scanner enforces this at commit time too).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

GATE = 0.90


def build_summary(report: dict, golden_entries: list[dict]) -> dict:
    """Pure: anonymous cluster mapping + per-cluster rows + pooled numbers."""
    order = [e["id"] for e in golden_entries]
    anon = {cid: f"cluster-{i + 1}" for i, cid in enumerate(order)}
    unknown = [c["cluster_id"] for c in report.get("clusters", []) if c["cluster_id"] not in anon]
    if unknown:
        raise ValueError(f"report references cluster(s) not in golden order: {unknown}")
    fact_counts = {e["id"]: len(e["load_bearing_facts"]) for e in golden_entries}

    rows = []
    for c in report.get("clusters", []):
        rows.append({
            "num": anon[c["cluster_id"]],
            "status": c.get("status"),
            "facts": fact_counts.get(c["cluster_id"], 0),
            "consensus": c.get("consensus_recall"),
            "recall_a": c.get("recall_a"),
            "recall_b": c.get("recall_b"),
            "contested": len(c.get("contested_ids", [])),
        })

    return {
        "mapping": anon,
        "rows": rows,
        "pooled": {k: report.get(k) for k in (
            "total_facts", "scored_fact_count", "consensus_count",
            "pooled_consensus_recall", "pooled_union_recall", "pooled_recall_a",
            "pooled_recall_b", "macro_consensus_recall", "contested_count",
            "adjudicated_count", "verdict")},
        "pipeline_failures": [anon[c] for c in report.get("pipeline_failure_cluster_ids", [])],
        "invalid": [anon[c] for c in report.get("invalid_cluster_ids", [])],
        "git_sha": report.get("git_sha"),
        "timestamp": report.get("timestamp"),
        "aggregation_version": (report.get("manifest") or {}).get("aggregation_version"),
    }


def render_markdown(summary: dict, *, title: str, source_report: str) -> str:
    p = summary["pooled"]
    lines = [
        f"# {title}",
        "",
        "Anonymized measurement summary generated by "
        "`scripts/emit-fact-recall-summary.py`. The full report with real cluster "
        f"ids, per-fact verdicts, evidence spans, and raw grader responses lives in the "
        f"private corpus repo (source: `{source_report}`). Cluster ids are "
        "anonymized as cluster-1..N in golden-file order.",
        "",
        "## Result",
        "",
        f"**Pooled consensus recall: {p['pooled_consensus_recall']:.1%} "
        f"({p['consensus_count']}/{p['scored_fact_count']}) — "
        f"verdict `{p['verdict']}` (gate >= {GATE:.0%}).**",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| recall_a | {p['pooled_recall_a']:.1%} |",
        f"| recall_b | {p['pooled_recall_b']:.1%} |",
        f"| consensus (both agree covered) | {p['pooled_consensus_recall']:.1%} ({p['consensus_count']}/{p['scored_fact_count']}) |",
        f"| union (either agrees) | {p['pooled_union_recall']:.1%} |",
        f"| macro (unweighted) | {p['macro_consensus_recall']:.1%} |",
        f"| contested facts | {p['contested_count']} |",
        f"| adjudicated facts | {p['adjudicated_count']} |",
        f"| total facts (all clusters) | {p['total_facts']} |",
        "",
        "## Per cluster (anonymized)",
        "",
        "| # | Status | Facts | Consensus | recall_a | recall_b | Contested |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in summary["rows"]:
        cons = f"{r['consensus']:.2f}" if r["consensus"] is not None else "-"
        ra = f"{r['recall_a']:.2f}" if r["recall_a"] is not None else "-"
        rb = f"{r['recall_b']:.2f}" if r["recall_b"] is not None else "-"
        lines.append(f"| {r['num']} | {r['status']} | {r['facts']} | {cons} | {ra} | {rb} | {r['contested']} |")
    if summary["pipeline_failures"]:
        lines.append("")
        lines.append(f"Pipeline failures (facts counted as misses): {', '.join(summary['pipeline_failures'])}")
    if summary["invalid"]:
        lines.append("")
        lines.append(f"Measurement-invalid clusters: {', '.join(summary['invalid'])}")
    lines += [
        "",
        f"Metadata: git `{summary['git_sha'][:10] if summary['git_sha'] else 'unknown'}` · "
        f"run timestamp `{summary['timestamp']}` · aggregation version "
        f"`{summary['aggregation_version'] or 'pre-manifest'}`",
        "",
    ]
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--report", type=Path, required=True, help="private fact-recall report JSON")
    p.add_argument("--golden", type=Path, required=True,
                   help="synthesis-clusters golden JSONL (defines anonymization order)")
    p.add_argument("--output", type=Path, default=None,
                   help="markdown destination (default docs/calibration/synthesis-fact-recall-summary.md)")
    p.add_argument("--title", default=None)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    report = json.loads(args.report.read_text(encoding="utf-8"))
    golden_entries = [json.loads(line) for line in args.golden.read_text().splitlines() if line.strip()]
    summary = build_summary(report, golden_entries)
    title = args.title or (f"Synthesis fact-recall measurement "
                           f"({(report.get('timestamp') or '')[:10]})")
    markdown = render_markdown(summary, title=title,
                               source_report=Path(args.report).name)
    output = args.output or (Path("docs") / "calibration" / "synthesis-fact-recall-summary.md")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"summary written: {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
